### PR TITLE
Initialize documentation

### PR DESCRIPTION
**Pull request by namurphy**
This PR was made using `sphinx-quickstart`.

### CODE REVIEW

**Comment by kuchtact** [comment]
@namurphy Is this ready to merge? I can't remember what we decided. Thanks for doing this though!

**Comment by namurphy** [comment]
Sure, I think it's ready!  

If `pip install sphinx` has already been run and `make` has been installed, the docs can be built by:

1. Entering `docs/`
2. Running `make html`

The source files are in `docs/source` and the index file for the build output will be at `docs/build/html/index.html`.

**Comment by kuchtact** [comment]
You are referring to running the sphinx stuff on a personal computer, yes? Also, is there a way to make it so somebody can easily download all the dependencies they need (sphinx, numpy, etc.?)

**Review by kuchtact — APPROVED** [review]
I think this all looks great! I'm not quite sure what I'm looking at but I trust you.

**Pull request merged**
