### PR TITLE
Switch the pytest runner to nox and update tested versions of Python

### PR DESCRIPTION
**Pull request by namurphy**
This PR makes the following changes:

 - 🧪 Added a Nox session for performing tests, and updated the GitHub workflow for CI to include these sessions.
 - ⬆️ Updated the versions of Python in `noxfile.py` and CI to be those released in the past 36 months (as per the convention recommended by [SPEC 0](https://scientific-python.org/specs/spec-0000/))
 - ✂️ Deleted `tox.ini`.
 - 🏷️ Renamed a Nox session from `build_docs` → `docs` to shorten the command, and for consistency with PlasmaPy.
 - 🏷️ Renamed CI workflows to be consistent with PlasmaPy

> [!IMPORTANT]
> Building docs now requires doing `nox -s docs`.

### CODE REVIEW

**Comment by kuchtact** [comment]
I'm running Ubuntu on my computer and I can only get MDSplus and pre-commit working for python 3.9. I think that MDSplus may work up to python 3.11 but I'm not totally sure. Should we be testing MDSplus on python 3.9 or skip past that?

**Comment by namurphy** [comment]
Will add Python 3.9 back in!

**Review by kuchtact — CHANGES_REQUESTED** [review]
Since the documentation building has a new command maybe change the `Creating Documentation` part of the `docs/source/installation.rst` file accordingly to reflect the new command. I think all that needs to be put in there is to run `nox -s docs`. I've added the installation of `nox` in a different location in pull request https://github.com/kuchtact/WiPPLPy/pull/27.

**Review by kuchtact — APPROVED** [review]
I fixed my previous requested changes so I think it's all good now!

**Comment by kuchtact** [comment]
pre-commit.ci autofix

**Pull request merged**
